version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: jenkins_test:1.0
    build:
      context: .
      dockerfile: ./DockerfileJenkins
    privileged: true
    user: root
    ports:
      - 8087:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: